#!/bin/bash

echo "🗑️  Menghapus proteksi Anti Akses Node View dan Servers List..."

# File paths
NODE_VIEW_PATH="/var/www/pterodactyl/resources/scripts/admin/nodes/view/1/index.blade.php"
SERVERS_LIST_PATH="/var/www/pterodactyl/resources/scripts/admin/servers/index.blade.php"
DETAILS_SERVICE_PATH="/var/www/pterodactyl/app/Services/Servers/DetailsModificationService.php"

# Backup directory
BACKUP_DIR="/root/backup_protection_$(date -u +"%Y-%m-%d-%H-%M-%S")"
mkdir -p "$BACKUP_DIR"

# Function to restore backup
restore_backup() {
    local file_path=$1
    local backup_pattern="${file_path}.bak_*"
    
    echo "🔍 Mencari backup untuk: $(basename $file_path)"
    
    # Find the latest backup file
    local latest_backup=$(ls -t $backup_pattern 2>/dev/null | head -n1)
    
    if [ -n "$latest_backup" ]; then
        echo "📦 Ditemukan backup: $(basename $latest_backup)"
        cp "$latest_backup" "$BACKUP_DIR/" 2>/dev/null
        mv "$latest_backup" "$file_path"
        echo "✅ Berhasil restore: $(basename $file_path)"
        return 0
    else
        echo "⚠️  Tidak ditemukan backup untuk: $(basename $file_path)"
        
        # Check if modified file exists and create fresh backup before removal
        if [ -f "$file_path" ]; then
            local current_backup="${BACKUP_DIR}/$(basename $file_path).current_$(date -u +"%Y%m%d%H%M%S")"
            cp "$file_path" "$current_backup"
            echo "💾 Backup file saat ini disimpan di: $current_backup"
            
            # Remove the modified file (will be regenerated by Pterodactyl)
            rm -f "$file_path"
            echo "🗑️  File modifikasi dihapus: $(basename $file_path)"
        fi
        return 1
    fi
}

echo "🔄 Memulai proses uninstall..."

# Restore Node View
echo ""
echo "📋 1. Restoring Node View..."
restore_backup "$NODE_VIEW_PATH"

# Restore Servers List
echo ""
echo "📋 2. Restoring Servers List..."
restore_backup "$SERVERS_LIST_PATH"

# Restore Details Modification Service
echo ""
echo "📋 3. Restoring Details Modification Service..."
restore_backup "$DETAILS_SERVICE_PATH"

echo ""
echo "=========================================="
echo "🎉 UNINSTALL SELESAI!"
echo "=========================================="
echo ""
echo "📊 Hasil Uninstall:"
echo "   ✅ Proteksi Node View dihapus"
echo "   ✅ Proteksi Servers List dihapus" 
echo "   ✅ Proteksi Details Modification Service dihapus"
echo ""
echo "💾 Backup files disimpan di: $BACKUP_DIR"
echo ""
echo "🔧 Langkah selanjutnya:"
echo "   1. Clear cache Pterodactyl jika diperlukan"
echo "   2. Restart worker queue jika ada perubahan service"
echo "   3. Verifikasi panel berjalan normal"
echo ""
echo "⚠️  Catatan: File asli akan digenerate ulang oleh Pterodactyl"
echo "    saat diakses jika backup tidak ditemukan."
